version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: mytravelline-postgres
    environment:
      POSTGRES_DB: mytravelline
      POSTGRES_USER: mytravelline
      POSTGRES_PASSWORD: mytravelline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
