spring:
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    com.mytravelline: INFO
    org.springframework.security: WARN
  pattern:
    console: '{"timestamp":"%d{ISO8601}","level":"%level","logger":"%logger","thread":"%thread","message":"%msg"}%n'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
